/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackgroundBox: typeof import('./src/components/controls/BackgroundBox.vue')['default']
    BarCopyright: typeof import('./src/components/controls/BarCopyright.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconLink: typeof import('./src/components/icons/IconLink.vue')['default']
    IconLove: typeof import('./src/components/icons/IconLove.vue')['default']
    IconMenu: typeof import('./src/components/icons/IconMenu.vue')['default']
    IconTranslate: typeof import('./src/components/icons/IconTranslate.vue')['default']
    IconUser: typeof import('./src/components/icons/IconUser.vue')['default']
    InputIconMenu: typeof import('./src/components/controls/InputIconMenu.vue')['default']
    MenuIcon: typeof import('./src/components/controls/MenuIcon.vue')['default']
    PluWeather: typeof import('./src/components/widgets/PluWeather.vue')['default']
    PluWord: typeof import('./src/components/widgets/PluWord.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/controls/SearchBox.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
